{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": "arn:aws:iam::316608166692:role/CodeStarWorker-contractors-CodeDeploy",
            "Condition": {
                "StringEquals": {
                    "iam:PassedToService": "codedeploy.amazonaws.com"
                }
            }
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "iam:DetachRolePolicy",
                "iam:DeleteRolePolicy",
                "iam:PutRolePermissionsBoundary",
                "iam:PutUserPermissionsBoundary",
                "iam:DeleteUserPolicy",
                "iam:AttachUserPolicy",
                "iam:CreateRole",
                "iam:AttachRolePolicy",
                "iam:DetachUserPolicy",
                "iam:CreateUser"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:PermissionsBoundary": "arn:aws:iam::316608166692:policy/CodeStar_contractors_PermissionsBoundary"
                }
            }
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "dynamodb:DeleteTable",
                "codedeploy:CreateDeploymentGroup",
                "kinesis:RemoveTagsFromStream",
                "ec2:StartInstances",
                "s3:PutLifecycleConfiguration",
                "dynamodb:DescribeContinuousBackups",
                "config:DescribeConfigRules",
                "events:RemoveTargets",
                "sns:Subscribe",
                "iam:GetRole",
                "events:DescribeRule",
                "sns:ListSubscriptionsByTopic",
                "dynamodb:UpdateTimeToLive",
                "codedeploy:DeleteDeploymentConfig",
                "codedeploy:RegisterApplicationRevision",
                "config:PutConfigRule",
                "ec2:CreateTags",
                "sns:CreateTopic",
                "s3:PutReplicationConfiguration",
                "ec2:RunInstances",
                "iam:DeleteRole",
                "ec2:StopInstances",
                "kms:DisableKey",
                "dynamodb:CreateTable",
                "s3:PutBucketNotification",
                "ec2:DisassociateIamInstanceProfile",
                "events:ListTagsForResource",
                "apigateway:POST",
                "ec2:DescribeSubnets",
                "kinesis:StartStreamEncryption",
                "dynamodb:UpdateTable",
                "ec2:AttachVolume",
                "kms:EnableKey",
                "kms:UntagResource",
                "codedeploy:CreateDeployment",
                "events:PutRule",
                "codedeploy:GetDeploymentConfig",
                "sns:ListTopics",
                "dynamodb:ListTagsOfResource",
                "codedeploy:CreateDeploymentConfig",
                "apigateway:DELETE",
                "kms:CreateKey",
                "s3:DeleteBucket",
                "s3:PutBucketVersioning",
                "ec2:ModifyInstancePlacement",
                "sns:GetTopicAttributes",
                "apigateway:PUT",
                "s3:PutMetricsConfiguration",
                "kinesis:DescribeStream",
                "iam:DeleteUser",
                "s3:PutInventoryConfiguration",
                "ec2:DescribeSecurityGroups",
                "events:DeleteRule",
                "sqs:TagQueue",
                "config:ListTagsForResource",
                "iam:CreateServiceLinkedRole",
                "s3:PutBucketWebsite",
                "kinesis:AddTagsToStream",
                "config:TagResource",
                "kms:CreateAlias",
                "kinesis:UpdateShardCount",
                "lambda:CreateAlias",
                "lambda:CreateFunction",
                "lambda:DeleteAlias",
                "lambda:DeleteFunction",
                "lambda:DeleteFunctionConcurrency",
                "lambda:GetFunction",
                "lambda:GetFunctionConfiguration",
                "lambda:ListTags",
                "lambda:ListVersionsByFunction",
                "lambda:PublishVersion",
                "lambda:PutFunctionConcurrency",
                "lambda:TagResource",
                "lambda:UntagResource",
                "lambda:UpdateAlias",
                "lambda:UpdateFunctionCode",
                "s3:PutAnalyticsConfiguration",
                "ec2:MonitorInstances",
                "sqs:UntagQueue",
                "sns:Unsubscribe",
                "s3:CreateBucket",
                "ec2:ReplaceIamInstanceProfileAssociation",
                "s3:DeleteBucketWebsite",
                "dynamodb:DescribeTable",
                "s3:PutBucketAcl",
                "apigateway:GET",
                "ec2:DetachVolume",
                "codedeploy:GetDeploymentGroup",
                "sqs:GetQueueUrl",
                "kinesis:CreateStream",
                "sqs:GetQueueAttributes",
                "s3:PutBucketCORS",
                "kinesis:DeleteStream",
                "s3:PutBucketLogging",
                "sqs:DeleteQueue",
                "codedeploy:DeleteApplication",
                "kms:DeleteAlias",
                "config:UntagResource",
                "codestar:SyncResources",
                "codedeploy:CreateApplication",
                "s3:PutAccelerateConfiguration",
                "sns:DeleteTopic",
                "kinesis:DecreaseStreamRetentionPeriod",
                "sqs:ListQueueTags",
                "dynamodb:UpdateContinuousBackups",
                "s3:PutEncryptionConfiguration",
                "kms:TagResource",
                "dynamodb:TagResource",
                "ec2:CreateSecurityGroup",
                "apigateway:PATCH",
                "kinesis:IncreaseStreamRetentionPeriod",
                "ec2:ModifyInstanceAttribute",
                "config:DeleteConfigRule",
                "kinesis:StopStreamEncryption",
                "s3:PutBucketPublicAccessBlock",
                "ec2:TerminateInstances",
                "dynamodb:UntagResource",
                "ec2:DescribeIamInstanceProfileAssociations",
                "dynamodb:DescribeTimeToLive",
                "kms:UpdateAlias",
                "codedeploy:DeleteDeploymentGroup",
                "events:TagResource",
                "events:PutTargets",
                "sns:SetSubscriptionAttributes",
                "ec2:ModifyInstanceCreditSpecification",
                "codedeploy:GetDeployment",
                "sqs:CreateQueue",
                "codedeploy:DeleteDeployment",
                "ec2:AssociateIamInstanceProfile",
                "events:UntagResource"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "iam:PassRole",
                "lambda:AddPermission",
                "cloudformation:CreateChangeSet",
                "lambda:RemovePermission",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "arn:aws:lambda:us-east-2:316608166692:function:awscodestar-contractors-infrastru-GetContractorsID-COGZDPDQ3D",
                "arn:aws:lambda:us-east-2:316608166692:function:awscodestar-contractors-infrastru-PutContractorsID-7Q1REVQ8X8DB",
                "arn:aws:lambda:us-east-2:316608166692:function:awscodestar-contractors-lambda-HelloWorld",
                "arn:aws:lambda:us-east-2:316608166692:function:awscodestar-contractors-infrastr-GetContractorsAll-5XLZOJVL58U5",
                "arn:aws:lambda:us-east-2:316608166692:function:awscodestar-contractors-infrastr-DeleteContractors-1GE1XXJOQB2BZ",
                "arn:aws:lambda:us-east-2:316608166692:function:awscodestar-contractors-infrastruc-PostContractors-T17JCQYGLNO6",
                "arn:aws:iam::316608166692:role/CodeStar-contractors*",
                "arn:aws:s3:::aws-codestar-us-east-2-316608166692-contractors-pipe/*",
                "arn:aws:s3:::aws-codestar-us-east-2-316608166692-contractors-pipe",
                "arn:aws:cloudformation:us-east-2:aws:transform/Serverless-2016-10-31",
                "arn:aws:cloudformation:us-east-2:aws:transform/CodeStar"
            ]
        },
        {
            "Sid": "VisualEditor4",
            "Effect": "Allow",
            "Action": "ssm:GetParameter*",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "ssm:ResourceTag/awscodestar:projectArn": "arn:aws:codestar:us-east-2:316608166692:project/contractors"
                }
            }
        }
    ]
}